name: PubSub Sink
language: python
variables:
  - name: input
    inputType: InputTopic
    description: This is the input topic
    defaultValue: postgres-cdc
    required: true
  - name: PROJECT_ID
    inputType: FreeText
    description: The BigQuery GCP Project ID
    defaultValue: portalanalytics-391408
    required: true
  - name: DATASET_ID
    inputType: FreeText
    description: The target BigQuery dataset ID
    defaultValue: sdfdev
    required: true
  - name: TOPIC_ID
    inputType: FreeText
    description: Name of the destination table.
    defaultValue: sdftest
    required: true
  - name: CONSUMER_GROUP
    inputType: FreeText
    description: Kafka consumer group.
    defaultValue: pubsub-sink-v1
    required: true
  - name: SERVICE_ACCOUNT_JSON
    inputType: Secret
    description: JSON string of the service account file for the BigQuery GCP project
    defaultValue: big_query_secret_json
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
