name: IcebergQuery
language: python
variables:
  - name: password
    inputType: Secret
    description: ''
    defaultValue: dashboard_passport
    required: true
  - name: TABLE_NAME
    inputType: FreeText
    description: ''
    defaultValue: gametelemtry-v3
    required: true
  - name: consumer_group
    inputType: FreeText
    defaultValue: iceberg-sink-v3.9
    required: false
  - name: leading_edge_ms
    inputType: FreeText
    defaultValue: 5000
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
