# Use the official Telegraf image for the final container
FROM quixanalytics/quix-telegraf:2024-28-11

# Copy custom Telegraf configuration
COPY telegraf.conf /etc/telegraf/telegraf.conf

# Default command to run Telegraf
CMD ["/usr/bin/telegraf", "--config", "/etc/telegraf/telegraf.conf"]